site_name: "rovera Security PSP"
site_description: "rovera Security Policies, Standards, and Procedures"
site_url: "http://www.bbc.com/security"
theme:
  name: material
  palette:
    primary: "blue" # Added a default color, you can change this
    accent: "orange" # Added a default color, you can change this
  favicon: "assets/images/favicon.ico"
  logo: "assets/images/logo.svg"

extra_css:
  - "assets/css/custom.css"

markdown_extensions:
  - smarty
  - toc:
      permalink: true
  - sane_lists
  - admonition
  - codehilite:
      guess_lang: false

nav:
  - Home: "index.md"
  - 0. Security Program Overview: "program.md"
  - 1. Corporate Governance: "corp-gov.md"
  - 2. Policy Management: "policy-mgmt.md"
  - 3. Security Architecture and Operating Model: "model.md"
  - 4. Roles, Responsibilities and Training: "rar.md"
  - 5. Risk Management and Risk Assessment Process: "risk-mgmt.md"
  - 6. Compliance Audits and External Communications: "compliance-audit.md"
  - 7. System Audits, Monitoring and Assessments: "system-audit.md"
  - 8. HR and Personnel Security: "hr.md"
  - 9. Access: "access.md"
  - 10. Facility Access and Physical Security: "facility.md"
  - 11. Asset Inventory Management: "asset-mgmt.md"
  - 12. Data Management: "data-mgmt.md"
  - 13. Data Protection: "data-protection.md"
  - 14. Secure Software Development and Product Security: "sdlc.md"
  - 15. Configuration and Change Management: "ccm.md"
  - 16. Threat Detection and Prevention: "threat.md"
  - 17. Vulnerability Management: "vuln-mgmt.md"
  - 18. Mobile Device Security and Media Management: "mdm.md"
  - 19. Business Continuity and Disaster Recovery: "bcdr.md"
  - 20. Incident Response: "ir.md"
  - 21. Breach Investigation and Notification: "breach.md"
  - 22. Third Party Security and Vendor Risk Management: "vendor.md"
  - 23. Privacy Practice and Consent: "privacy.md"
  - 24. Addendum and References: "ref.md"
  - Appendices:
      - A. Employee Handbook: "employee-handbook.md"
      - B. Approved Software: "approved-software.md"
      - C. Approved Vendors: "approved-vendors.md"
      - D. Key Definitions: "definitions.md"
      - E. HIPAA Business Associate Agreement: "hipaa-baa.md"
      - F. HIPAA Controls Mapping: "hipaa-mapping.md"
      - G. NIST Controls Mapping: "nist-mapping.md"
      - H. Privacy Policy: "privacy-policy.md"
      - I. Cookie Policy: "cookie-policy.md"
      - J. GDPR Data Processing Agreement: "gdpr-dpa.md"
